
// This file has been generated by the GUI designer. Do not modify.
namespace Nebuchadnezzar
{
	public partial class LoginWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry serverEntry;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry usernameEntry;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry passwordEntry;
		
		private global::Gtk.HButtonBox hbuttonbox1;
		
		private global::Gtk.Button quitButton;
		
		private global::Gtk.Button loginButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Nebuchadnezzar.LoginWindow
			this.Name = "Nebuchadnezzar.LoginWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("LoginWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child Nebuchadnezzar.LoginWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Matrix server");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.serverEntry = new global::Gtk.Entry ();
			this.serverEntry.CanFocus = true;
			this.serverEntry.Name = "serverEntry";
			this.serverEntry.Text = global::Mono.Unix.Catalog.GetString ("http://matrix.org");
			this.serverEntry.IsEditable = true;
			this.serverEntry.InvisibleChar = '●';
			this.vbox1.Add (this.serverEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.serverEntry]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Username");
			this.vbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.usernameEntry = new global::Gtk.Entry ();
			this.usernameEntry.CanFocus = true;
			this.usernameEntry.Name = "usernameEntry";
			this.usernameEntry.IsEditable = true;
			this.usernameEntry.InvisibleChar = '●';
			this.vbox1.Add (this.usernameEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.usernameEntry]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.vbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.passwordEntry = new global::Gtk.Entry ();
			this.passwordEntry.CanFocus = true;
			this.passwordEntry.Name = "passwordEntry";
			this.passwordEntry.IsEditable = true;
			this.passwordEntry.InvisibleChar = '●';
			this.vbox1.Add (this.passwordEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.passwordEntry]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.quitButton = new global::Gtk.Button ();
			this.quitButton.CanFocus = true;
			this.quitButton.Name = "quitButton";
			this.quitButton.UseUnderline = true;
			this.quitButton.Label = global::Mono.Unix.Catalog.GetString ("Quit");
			this.hbuttonbox1.Add (this.quitButton);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.quitButton]));
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.loginButton = new global::Gtk.Button ();
			this.loginButton.CanFocus = true;
			this.loginButton.Name = "loginButton";
			this.loginButton.UseUnderline = true;
			this.loginButton.Label = global::Mono.Unix.Catalog.GetString ("Log in");
			this.hbuttonbox1.Add (this.loginButton);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.loginButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w9.PackType = ((global::Gtk.PackType)(1));
			w9.Position = 6;
			w9.Expand = false;
			w9.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 229;
			this.Show ();
			this.loginButton.Activated += new global::System.EventHandler (this.onLogin);
			this.loginButton.Clicked += new global::System.EventHandler (this.onLogin);
		}
	}
}
